/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import { GraphQLSchema, GraphQLObjectType, GraphQLInterfaceType, GraphQLNonNull, GraphQLID, GraphQLList, GraphQLString, GraphQLInt, GraphQLEnumType, GraphQLBoolean } from "graphql";
import { node as queryNodeResolver, id as storyIdResolver, id as organizationIdResolver, id as personIdResolver } from "./data/graphql/node.ts";
import { Story as queryTopStoriesResolver, Story as queryTopStoryResolver, Story as mutationLikeStoryResolver, Story as mutationPostStoryCommentResolver } from "./data/models/story.ts";
import { Viewer as queryViewerResolver } from "./data/models/viewer.ts";
import { joined as organizationJoinedResolver, name as organizationNameResolver, profilePicture as organizationProfilePictureResolver, joined as personJoinedResolver, name as personNameResolver, profilePicture as personProfilePictureResolver } from "./data/graphql/actor.ts";
export function getSchema(): GraphQLSchema {
    const NodeType: GraphQLInterfaceType = new GraphQLInterfaceType({
        name: "Node",
        fields() {
            return {
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const ImageType: GraphQLObjectType = new GraphQLObjectType({
        name: "Image",
        fields() {
            return {
                altText: {
                    name: "altText",
                    type: GraphQLString
                },
                url: {
                    name: "url",
                    type: new GraphQLNonNull(GraphQLString),
                    args: {
                        height: {
                            type: GraphQLInt
                        },
                        width: {
                            type: GraphQLInt
                        }
                    },
                    resolve(source, args) {
                        return source.url(args.height, args.width);
                    }
                }
            };
        }
    });
    const CategoryType: GraphQLEnumType = new GraphQLEnumType({
        name: "Category",
        values: {
            ALL: {
                value: "ALL"
            },
            COOKING: {
                value: "COOKING"
            },
            EDUCATION: {
                value: "EDUCATION"
            },
            NEWS: {
                value: "NEWS"
            }
        }
    });
    const CommentType: GraphQLObjectType = new GraphQLObjectType({
        name: "Comment",
        fields() {
            return {
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                text: {
                    name: "text",
                    type: GraphQLString
                }
            };
        }
    });
    const CommentEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "CommentEdge",
        fields() {
            return {
                cursor: {
                    name: "cursor",
                    type: GraphQLString
                },
                node: {
                    name: "node",
                    type: CommentType
                }
            };
        }
    });
    const PageInfoType: GraphQLObjectType = new GraphQLObjectType({
        name: "PageInfo",
        fields() {
            return {
                endCursor: {
                    name: "endCursor",
                    type: GraphQLString
                },
                hasNextPage: {
                    name: "hasNextPage",
                    type: GraphQLBoolean
                },
                hasPreviousPage: {
                    name: "hasPreviousPage",
                    type: GraphQLBoolean
                },
                lastCursor: {
                    name: "lastCursor",
                    type: GraphQLString
                },
                startCursor: {
                    name: "startCursor",
                    type: GraphQLString
                }
            };
        }
    });
    const CommentConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "CommentConnection",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLList(CommentEdgeType)
                },
                pageInfo: {
                    name: "pageInfo",
                    type: PageInfoType
                }
            };
        }
    });
    const ActorType: GraphQLInterfaceType = new GraphQLInterfaceType({
        name: "Actor",
        fields() {
            return {
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                joined: {
                    name: "joined",
                    type: GraphQLString
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                profilePicture: {
                    name: "profilePicture",
                    type: ImageType
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const StoryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Story",
        fields() {
            return {
                attachments: {
                    name: "attachments",
                    type: new GraphQLList(new GraphQLNonNull(ImageType))
                },
                category: {
                    name: "category",
                    type: CategoryType
                },
                comments: {
                    name: "comments",
                    type: CommentConnectionType,
                    args: {
                        after: {
                            type: GraphQLString
                        },
                        first: {
                            type: GraphQLInt
                        }
                    },
                    resolve(source, args) {
                        return source.comments(args.first, args.after);
                    }
                },
                createdAt: {
                    name: "createdAt",
                    type: new GraphQLNonNull(GraphQLString)
                },
                doesViewerLike: {
                    name: "doesViewerLike",
                    type: GraphQLBoolean
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return storyIdResolver(source);
                    }
                },
                likeCount: {
                    name: "likeCount",
                    type: GraphQLInt
                },
                poster: {
                    name: "poster",
                    type: new GraphQLNonNull(ActorType)
                },
                summary: {
                    name: "summary",
                    type: GraphQLString
                },
                thumbnail: {
                    name: "thumbnail",
                    type: ImageType
                },
                title: {
                    name: "title",
                    type: new GraphQLNonNull(GraphQLString)
                },
                updatedAt: {
                    name: "updatedAt",
                    type: GraphQLString
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const StoryEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "StoryEdge",
        fields() {
            return {
                cursor: {
                    name: "cursor",
                    type: GraphQLString
                },
                node: {
                    name: "node",
                    type: StoryType
                }
            };
        }
    });
    const StoryConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "StoryConnection",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLList(StoryEdgeType)
                },
                pageInfo: {
                    name: "pageInfo",
                    type: PageInfoType
                }
            };
        }
    });
    const ViewerType: GraphQLObjectType = new GraphQLObjectType({
        name: "Viewer",
        fields() {
            return {
                actor: {
                    name: "actor",
                    type: ActorType
                },
                contacts: {
                    name: "contacts",
                    type: new GraphQLList(new GraphQLNonNull(ActorType)),
                    args: {
                        search: {
                            type: GraphQLString
                        }
                    },
                    resolve(source, args) {
                        return source.contacts(args.search);
                    }
                },
                newsfeedStories: {
                    name: "newsfeedStories",
                    type: StoryConnectionType,
                    args: {
                        after: {
                            type: GraphQLString
                        },
                        category: {
                            type: CategoryType
                        },
                        first: {
                            type: GraphQLInt
                        }
                    },
                    resolve(source, args) {
                        return source.newsfeedStories(args.first, args.after, args.category);
                    }
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                node: {
                    name: "node",
                    type: NodeType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return queryNodeResolver(args.id);
                    }
                },
                topStories: {
                    name: "topStories",
                    type: new GraphQLList(new GraphQLNonNull(StoryType)),
                    resolve() {
                        return queryTopStoriesResolver.topStories();
                    }
                },
                topStory: {
                    name: "topStory",
                    type: StoryType,
                    args: {
                        category: {
                            type: CategoryType
                        }
                    },
                    resolve(_source, args) {
                        return queryTopStoryResolver.topStory(args.category);
                    }
                },
                viewer: {
                    name: "viewer",
                    type: ViewerType,
                    resolve() {
                        return queryViewerResolver.viewer();
                    }
                }
            };
        }
    });
    const StoryMutationResponseType: GraphQLObjectType = new GraphQLObjectType({
        name: "StoryMutationResponse",
        fields() {
            return {
                story: {
                    name: "story",
                    type: StoryType
                }
            };
        }
    });
    const StoryCommentMutationResponseType: GraphQLObjectType = new GraphQLObjectType({
        name: "StoryCommentMutationResponse",
        fields() {
            return {
                commentEdge: {
                    name: "commentEdge",
                    type: CommentEdgeType
                },
                story: {
                    name: "story",
                    type: StoryType
                }
            };
        }
    });
    const MutationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Mutation",
        fields() {
            return {
                likeStory: {
                    name: "likeStory",
                    type: StoryMutationResponseType,
                    args: {
                        doesLike: {
                            type: new GraphQLNonNull(GraphQLBoolean)
                        },
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return mutationLikeStoryResolver.likeStory(args.id, args.doesLike);
                    }
                },
                postStoryComment: {
                    name: "postStoryComment",
                    type: StoryCommentMutationResponseType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        },
                        text: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return mutationPostStoryCommentResolver.postStoryComment(args.id, args.text);
                    }
                }
            };
        }
    });
    const OrganizationKindType: GraphQLEnumType = new GraphQLEnumType({
        name: "OrganizationKind",
        values: {
            COMMERCIAL: {
                value: "COMMERCIAL"
            },
            GOVERNMENT: {
                value: "GOVERNMENT"
            },
            JOURNALISTIC: {
                value: "JOURNALISTIC"
            },
            NONPROFIT: {
                value: "NONPROFIT"
            }
        }
    });
    const LocationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Location",
        fields() {
            return {
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                name: {
                    name: "name",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const OrganizationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Organization",
        fields() {
            return {
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return organizationIdResolver(source);
                    }
                },
                joined: {
                    name: "joined",
                    type: GraphQLString,
                    resolve(source) {
                        return organizationJoinedResolver(source);
                    }
                },
                name: {
                    name: "name",
                    type: GraphQLString,
                    resolve(source) {
                        return organizationNameResolver(source);
                    }
                },
                organizationKind: {
                    name: "organizationKind",
                    type: OrganizationKindType
                },
                profilePicture: {
                    name: "profilePicture",
                    type: ImageType,
                    resolve(source) {
                        return organizationProfilePictureResolver(source);
                    }
                }
            };
        },
        interfaces() {
            return [ActorType, NodeType];
        }
    });
    const PersonType: GraphQLObjectType = new GraphQLObjectType({
        name: "Person",
        fields() {
            return {
                email: {
                    name: "email",
                    type: GraphQLString
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return personIdResolver(source);
                    }
                },
                joined: {
                    name: "joined",
                    type: GraphQLString,
                    resolve(source) {
                        return personJoinedResolver(source);
                    }
                },
                location: {
                    name: "location",
                    type: LocationType
                },
                name: {
                    name: "name",
                    type: GraphQLString,
                    resolve(source) {
                        return personNameResolver(source);
                    }
                },
                profilePicture: {
                    name: "profilePicture",
                    type: ImageType,
                    resolve(source) {
                        return personProfilePictureResolver(source);
                    }
                }
            };
        },
        interfaces() {
            return [ActorType, NodeType];
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        mutation: MutationType,
        types: [CategoryType, OrganizationKindType, ActorType, NodeType, CommentType, CommentConnectionType, CommentEdgeType, ImageType, LocationType, MutationType, OrganizationType, PageInfoType, PersonType, QueryType, StoryType, StoryCommentMutationResponseType, StoryConnectionType, StoryEdgeType, StoryMutationResponseType, ViewerType]
    });
}
