/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import { GraphQLSchema, GraphQLObjectType, GraphQLInterfaceType, GraphQLNonNull, GraphQLID, GraphQLInt, GraphQLList, GraphQLString, GraphQLBoolean, GraphQLInputObjectType } from "graphql";
import { node as queryNodeResolver, id as userIdResolver, id as todoIdResolver } from "./data/graphql/node.ts";
import { User as queryUserResolver } from "./data/models/user.ts";
import { Todo as mutationAddTodoResolver, Todo as mutationChangeTodoStatusResolver, Todo as mutationMarkAllTodosResolver, Todo as mutationRemoveCompletedTodosResolver, Todo as mutationRemoveTodoResolver, Todo as mutationRenameTodoResolver } from "./data/models/todo.ts";
export function getSchema(): GraphQLSchema {
    const NodeType: GraphQLInterfaceType = new GraphQLInterfaceType({
        description: "An object with an ID",
        name: "Node",
        fields() {
            return {
                id: {
                    description: "The id of the object.",
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const TodoType: GraphQLObjectType = new GraphQLObjectType({
        name: "Todo",
        fields() {
            return {
                complete: {
                    name: "complete",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                id: {
                    description: "The id of the object.",
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return todoIdResolver(source);
                    }
                },
                text: {
                    name: "text",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const TodoEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "TodoEdge",
        description: "An edge in a connection.",
        fields() {
            return {
                cursor: {
                    description: "A cursor for use in pagination",
                    name: "cursor",
                    type: new GraphQLNonNull(GraphQLString)
                },
                node: {
                    description: "The item at the end of the edge",
                    name: "node",
                    type: TodoType
                }
            };
        }
    });
    const PageInfoType: GraphQLObjectType = new GraphQLObjectType({
        name: "PageInfo",
        description: "Information about pagination in a connection.",
        fields() {
            return {
                endCursor: {
                    description: "When paginating forwards, the cursor to continue.",
                    name: "endCursor",
                    type: GraphQLString
                },
                hasNextPage: {
                    description: "When paginating forwards, are there more items?",
                    name: "hasNextPage",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                hasPreviousPage: {
                    description: "When paginating backwards, are there more items?",
                    name: "hasPreviousPage",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                startCursor: {
                    description: "When paginating backwards, the cursor to continue.",
                    name: "startCursor",
                    type: GraphQLString
                }
            };
        }
    });
    const TodoConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "TodoConnection",
        description: "A connection to a list of items.",
        fields() {
            return {
                edges: {
                    description: "A list of edges.",
                    name: "edges",
                    type: new GraphQLList(TodoEdgeType)
                },
                pageInfo: {
                    description: "Information to aid in pagination.",
                    name: "pageInfo",
                    type: new GraphQLNonNull(PageInfoType)
                }
            };
        }
    });
    const UserType: GraphQLObjectType = new GraphQLObjectType({
        name: "User",
        fields() {
            return {
                completedCount: {
                    name: "completedCount",
                    type: new GraphQLNonNull(GraphQLInt)
                },
                id: {
                    description: "The id of the object.",
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID),
                    resolve(source) {
                        return userIdResolver(source);
                    }
                },
                todos: {
                    name: "todos",
                    type: TodoConnectionType,
                    args: {
                        after: {
                            type: GraphQLString
                        },
                        before: {
                            type: GraphQLString
                        },
                        first: {
                            type: GraphQLInt
                        },
                        last: {
                            type: GraphQLInt
                        },
                        status: {
                            type: GraphQLString,
                            defaultValue: "any"
                        }
                    },
                    resolve(source, args) {
                        return source.todos(args.status, args.after, args.first, args.before, args.last);
                    }
                },
                totalCount: {
                    name: "totalCount",
                    type: new GraphQLNonNull(GraphQLInt)
                },
                userId: {
                    name: "userId",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        },
        interfaces() {
            return [NodeType];
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                node: {
                    description: "Fetches an object given its ID",
                    name: "node",
                    type: NodeType,
                    args: {
                        id: {
                            description: "The ID of an object",
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return queryNodeResolver(args.id);
                    }
                },
                user: {
                    name: "user",
                    type: UserType,
                    args: {
                        id: {
                            type: GraphQLString
                        }
                    },
                    resolve(_source, args) {
                        return queryUserResolver.user(args.id);
                    }
                }
            };
        }
    });
    const AddTodoPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "AddTodoPayload",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                todoEdge: {
                    name: "todoEdge",
                    type: new GraphQLNonNull(TodoEdgeType)
                },
                user: {
                    name: "user",
                    type: new GraphQLNonNull(UserType)
                }
            };
        }
    });
    const AddTodoInputType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "AddTodoInput",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                text: {
                    name: "text",
                    type: new GraphQLNonNull(GraphQLString)
                },
                userId: {
                    name: "userId",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const ChangeTodoStatusPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "ChangeTodoStatusPayload",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                todo: {
                    name: "todo",
                    type: new GraphQLNonNull(TodoType)
                },
                user: {
                    name: "user",
                    type: new GraphQLNonNull(UserType)
                }
            };
        }
    });
    const ChangeTodoStatusInputType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "ChangeTodoStatusInput",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                complete: {
                    name: "complete",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                userId: {
                    name: "userId",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const MarkAllTodosPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "MarkAllTodosPayload",
        fields() {
            return {
                changedTodos: {
                    name: "changedTodos",
                    type: new GraphQLList(new GraphQLNonNull(TodoType))
                },
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                user: {
                    name: "user",
                    type: new GraphQLNonNull(UserType)
                }
            };
        }
    });
    const MarkAllTodosInputType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "MarkAllTodosInput",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                complete: {
                    name: "complete",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                userId: {
                    name: "userId",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const RemoveCompletedTodosPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "RemoveCompletedTodosPayload",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                deletedTodoIds: {
                    name: "deletedTodoIds",
                    type: new GraphQLList(new GraphQLNonNull(GraphQLID))
                },
                user: {
                    name: "user",
                    type: new GraphQLNonNull(UserType)
                }
            };
        }
    });
    const RemoveCompletedTodosInputType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "RemoveCompletedTodosInput",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                userId: {
                    name: "userId",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const RemoveTodoPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "RemoveTodoPayload",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                deletedTodoId: {
                    name: "deletedTodoId",
                    type: new GraphQLNonNull(GraphQLID)
                },
                user: {
                    name: "user",
                    type: new GraphQLNonNull(UserType)
                }
            };
        }
    });
    const RemoveTodoInputType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "RemoveTodoInput",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                userId: {
                    name: "userId",
                    type: new GraphQLNonNull(GraphQLID)
                }
            };
        }
    });
    const RenameTodoPayloadType: GraphQLObjectType = new GraphQLObjectType({
        name: "RenameTodoPayload",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                todo: {
                    name: "todo",
                    type: new GraphQLNonNull(TodoType)
                }
            };
        }
    });
    const RenameTodoInputType: GraphQLInputObjectType = new GraphQLInputObjectType({
        name: "RenameTodoInput",
        fields() {
            return {
                clientMutationId: {
                    name: "clientMutationId",
                    type: GraphQLString
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                text: {
                    name: "text",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const MutationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Mutation",
        fields() {
            return {
                addTodo: {
                    name: "addTodo",
                    type: AddTodoPayloadType,
                    args: {
                        input: {
                            type: new GraphQLNonNull(AddTodoInputType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationAddTodoResolver.addTodo(args.input);
                    }
                },
                changeTodoStatus: {
                    name: "changeTodoStatus",
                    type: ChangeTodoStatusPayloadType,
                    args: {
                        input: {
                            type: new GraphQLNonNull(ChangeTodoStatusInputType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationChangeTodoStatusResolver.changeTodoStatus(args.input);
                    }
                },
                markAllTodos: {
                    name: "markAllTodos",
                    type: MarkAllTodosPayloadType,
                    args: {
                        input: {
                            type: new GraphQLNonNull(MarkAllTodosInputType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationMarkAllTodosResolver.markAllTodos(args.input);
                    }
                },
                removeCompletedTodos: {
                    name: "removeCompletedTodos",
                    type: RemoveCompletedTodosPayloadType,
                    args: {
                        input: {
                            type: new GraphQLNonNull(RemoveCompletedTodosInputType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationRemoveCompletedTodosResolver.removeCompletedTodos(args.input);
                    }
                },
                removeTodo: {
                    name: "removeTodo",
                    type: RemoveTodoPayloadType,
                    args: {
                        input: {
                            type: new GraphQLNonNull(RemoveTodoInputType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationRemoveTodoResolver.removeTodo(args.input);
                    }
                },
                renameTodo: {
                    name: "renameTodo",
                    type: RenameTodoPayloadType,
                    args: {
                        input: {
                            type: new GraphQLNonNull(RenameTodoInputType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationRenameTodoResolver.renameTodo(args.input);
                    }
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        mutation: MutationType,
        types: [NodeType, AddTodoInputType, ChangeTodoStatusInputType, MarkAllTodosInputType, RemoveCompletedTodosInputType, RemoveTodoInputType, RenameTodoInputType, AddTodoPayloadType, ChangeTodoStatusPayloadType, MarkAllTodosPayloadType, MutationType, PageInfoType, QueryType, RemoveCompletedTodosPayloadType, RemoveTodoPayloadType, RenameTodoPayloadType, TodoType, TodoConnectionType, TodoEdgeType, UserType]
    });
}
