// flow-typed signature: e98e7f3ab39a6e2d9b220227c4167bad
// flow-typed version: <<STUB>>/babel-plugin-relay_v8.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-relay/babel-plugin-relay' {
  declare module.exports: any;
}

declare module 'babel-plugin-relay/babel-plugin-relay.min' {
  declare module.exports: any;
}

declare module 'babel-plugin-relay/lib/BabelPluginRelay' {
  declare module.exports: any;
}

declare module 'babel-plugin-relay/lib/BabelPluginRelay.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-relay/lib/compileGraphQLTag' {
  declare module.exports: any;
}

declare module 'babel-plugin-relay/lib/createModernNode' {
  declare module.exports: any;
}

declare module 'babel-plugin-relay/lib/getValidGraphQLTag' {
  declare module.exports: any;
}

declare module 'babel-plugin-relay/macro' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-relay/babel-plugin-relay.js' {
  declare module.exports: $Exports<'babel-plugin-relay/babel-plugin-relay'>;
}
declare module 'babel-plugin-relay/babel-plugin-relay.min.js' {
  declare module.exports: $Exports<'babel-plugin-relay/babel-plugin-relay.min'>;
}
declare module 'babel-plugin-relay/index' {
  declare module.exports: $Exports<'babel-plugin-relay'>;
}
declare module 'babel-plugin-relay/index.js' {
  declare module.exports: $Exports<'babel-plugin-relay'>;
}
declare module 'babel-plugin-relay/lib/BabelPluginRelay.js' {
  declare module.exports: $Exports<'babel-plugin-relay/lib/BabelPluginRelay'>;
}
declare module 'babel-plugin-relay/lib/BabelPluginRelay.macro.js' {
  declare module.exports: $Exports<'babel-plugin-relay/lib/BabelPluginRelay.macro'>;
}
declare module 'babel-plugin-relay/lib/compileGraphQLTag.js' {
  declare module.exports: $Exports<'babel-plugin-relay/lib/compileGraphQLTag'>;
}
declare module 'babel-plugin-relay/lib/createModernNode.js' {
  declare module.exports: $Exports<'babel-plugin-relay/lib/createModernNode'>;
}
declare module 'babel-plugin-relay/lib/getValidGraphQLTag.js' {
  declare module.exports: $Exports<'babel-plugin-relay/lib/getValidGraphQLTag'>;
}
declare module 'babel-plugin-relay/macro.js' {
  declare module.exports: $Exports<'babel-plugin-relay/macro'>;
}
