// flow-typed signature: 5b97c059e7a6bf3f9d7e5ea4b0dc2753
// flow-typed version: <<STUB>>/eslint-config-fbjs_v^2.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-fbjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-fbjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-fbjs/shared' {
  declare module.exports: any;
}

declare module 'eslint-config-fbjs/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-fbjs/utils/change-error-level' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-fbjs/index' {
  declare module.exports: $Exports<'eslint-config-fbjs'>;
}
declare module 'eslint-config-fbjs/index.js' {
  declare module.exports: $Exports<'eslint-config-fbjs'>;
}
declare module 'eslint-config-fbjs/shared.js' {
  declare module.exports: $Exports<'eslint-config-fbjs/shared'>;
}
declare module 'eslint-config-fbjs/strict.js' {
  declare module.exports: $Exports<'eslint-config-fbjs/strict'>;
}
declare module 'eslint-config-fbjs/utils/change-error-level.js' {
  declare module.exports: $Exports<'eslint-config-fbjs/utils/change-error-level'>;
}
