// flow-typed signature: 24a5150a58bb1ea74840696ab60871ab
// flow-typed version: <<STUB>>/react-relay_v^3.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-relay/lib/assertFragmentMap' {
  declare module.exports: any;
}

declare module 'react-relay/lib/buildReactRelayContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/isRelayEnvironment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/isRelayVariables' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayContainerProfiler' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayContainerUtils' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayContext' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayFragmentContainer-flowtest' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayFragmentContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayFragmentMockRenderer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayPaginationContainer-flowtest' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayPaginationContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayPublic' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayQueryFetcher' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayQueryRenderer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayRefetchContainer-flowtest' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayRefetchContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayTestMocker' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayTypes' {
  declare module.exports: any;
}

declare module 'react-relay/lib/readContext' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayContext' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayModern-flowtest' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayModernFlowtest_badref.graphql' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayModernFlowtest_notref.graphql' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayModernFlowtest_user.graphql' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayModernFlowtest_users.graphql' {
  declare module.exports: any;
}

declare module 'react-relay/react-relay' {
  declare module.exports: any;
}

declare module 'react-relay/react-relay.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-relay/index' {
  declare module.exports: $Exports<'react-relay'>;
}
declare module 'react-relay/index.js' {
  declare module.exports: $Exports<'react-relay'>;
}
declare module 'react-relay/lib/assertFragmentMap.js' {
  declare module.exports: $Exports<'react-relay/lib/assertFragmentMap'>;
}
declare module 'react-relay/lib/buildReactRelayContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/buildReactRelayContainer'>;
}
declare module 'react-relay/lib/isRelayEnvironment.js' {
  declare module.exports: $Exports<'react-relay/lib/isRelayEnvironment'>;
}
declare module 'react-relay/lib/isRelayVariables.js' {
  declare module.exports: $Exports<'react-relay/lib/isRelayVariables'>;
}
declare module 'react-relay/lib/ReactRelayContainerProfiler.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayContainerProfiler'>;
}
declare module 'react-relay/lib/ReactRelayContainerUtils.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayContainerUtils'>;
}
declare module 'react-relay/lib/ReactRelayContext.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayContext'>;
}
declare module 'react-relay/lib/ReactRelayFragmentContainer-flowtest.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayFragmentContainer-flowtest'>;
}
declare module 'react-relay/lib/ReactRelayFragmentContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayFragmentContainer'>;
}
declare module 'react-relay/lib/ReactRelayFragmentMockRenderer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayFragmentMockRenderer'>;
}
declare module 'react-relay/lib/ReactRelayPaginationContainer-flowtest.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayPaginationContainer-flowtest'>;
}
declare module 'react-relay/lib/ReactRelayPaginationContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayPaginationContainer'>;
}
declare module 'react-relay/lib/ReactRelayPublic.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayPublic'>;
}
declare module 'react-relay/lib/ReactRelayQueryFetcher.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayQueryFetcher'>;
}
declare module 'react-relay/lib/ReactRelayQueryRenderer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayQueryRenderer'>;
}
declare module 'react-relay/lib/ReactRelayRefetchContainer-flowtest.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayRefetchContainer-flowtest'>;
}
declare module 'react-relay/lib/ReactRelayRefetchContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayRefetchContainer'>;
}
declare module 'react-relay/lib/ReactRelayTestMocker.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayTestMocker'>;
}
declare module 'react-relay/lib/ReactRelayTypes.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayTypes'>;
}
declare module 'react-relay/lib/readContext.js' {
  declare module.exports: $Exports<'react-relay/lib/readContext'>;
}
declare module 'react-relay/lib/RelayContext.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayContext'>;
}
declare module 'react-relay/lib/RelayModern-flowtest.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayModern-flowtest'>;
}
declare module 'react-relay/lib/RelayModernFlowtest_badref.graphql.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayModernFlowtest_badref.graphql'>;
}
declare module 'react-relay/lib/RelayModernFlowtest_notref.graphql.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayModernFlowtest_notref.graphql'>;
}
declare module 'react-relay/lib/RelayModernFlowtest_user.graphql.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayModernFlowtest_user.graphql'>;
}
declare module 'react-relay/lib/RelayModernFlowtest_users.graphql.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayModernFlowtest_users.graphql'>;
}
declare module 'react-relay/react-relay.js' {
  declare module.exports: $Exports<'react-relay/react-relay'>;
}
declare module 'react-relay/react-relay.min.js' {
  declare module.exports: $Exports<'react-relay/react-relay.min'>;
}
