// flow-typed signature: 218a0a97ca75427fc1e157fec5d07ddb
// flow-typed version: <<STUB>>/react-relay_v8.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-relay/hooks' {
  declare module.exports: any;
}

declare module 'react-relay/lib/assertFragmentMap' {
  declare module.exports: any;
}

declare module 'react-relay/lib/buildReactRelayContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/getRootVariablesForFragments' {
  declare module.exports: any;
}

declare module 'react-relay/lib/hooks' {
  declare module.exports: any;
}

declare module 'react-relay/lib' {
  declare module.exports: any;
}

declare module 'react-relay/lib/isRelayEnvironment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayContainerUtils' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayContext' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayFragmentContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayFragmentMockRenderer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayLocalQueryRenderer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayPaginationContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayQueryFetcher' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayQueryRenderer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayRefetchContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayTestMocker' {
  declare module.exports: any;
}

declare module 'react-relay/lib/ReactRelayTypes' {
  declare module.exports: any;
}

declare module 'react-relay/lib/readContext' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/EntryPointContainer.react' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/EntryPointTypes.flow' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/fetchQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/FragmentResource' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/getPaginationMetadata' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/getPaginationVariables' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/getRefetchMetadata' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/getValueAtPath' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/InternalLogger' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/LazyLoadEntryPointContainer.react' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/LRUCache' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/MatchContainer' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/preloadQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/prepareEntryPoint' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/ProfilerContext' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/QueryResource' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/RelayEnvironmentProvider' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useBlockingPaginationFragment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useConnection' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useFetchTrackingRef' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useFragment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useFragmentNode' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useFragmentNodes' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useIsMountedRef' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useIsParentQueryInFlight' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useLazyLoadQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useLazyLoadQueryNode' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useLegacyPaginationFragment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useLoadMoreFunction' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useMemoOperationDescriptor' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useMemoVariables' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/usePreloadedQuery' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useRefetchableFragment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useRefetchableFragmentNode' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useRelayEnvironment' {
  declare module.exports: any;
}

declare module 'react-relay/lib/relay-experimental/useStaticFragmentNodeWarning' {
  declare module.exports: any;
}

declare module 'react-relay/lib/RelayContext' {
  declare module.exports: any;
}

declare module 'react-relay/react-relay-hooks' {
  declare module.exports: any;
}

declare module 'react-relay/react-relay-hooks.min' {
  declare module.exports: any;
}

declare module 'react-relay/react-relay' {
  declare module.exports: any;
}

declare module 'react-relay/react-relay.min' {
  declare module.exports: any;
}

declare module 'react-relay/ReactRelayContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-relay/hooks.js' {
  declare module.exports: $Exports<'react-relay/hooks'>;
}
declare module 'react-relay/index' {
  declare module.exports: $Exports<'react-relay'>;
}
declare module 'react-relay/index.js' {
  declare module.exports: $Exports<'react-relay'>;
}
declare module 'react-relay/lib/assertFragmentMap.js' {
  declare module.exports: $Exports<'react-relay/lib/assertFragmentMap'>;
}
declare module 'react-relay/lib/buildReactRelayContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/buildReactRelayContainer'>;
}
declare module 'react-relay/lib/getRootVariablesForFragments.js' {
  declare module.exports: $Exports<'react-relay/lib/getRootVariablesForFragments'>;
}
declare module 'react-relay/lib/hooks.js' {
  declare module.exports: $Exports<'react-relay/lib/hooks'>;
}
declare module 'react-relay/lib/index' {
  declare module.exports: $Exports<'react-relay/lib'>;
}
declare module 'react-relay/lib/index.js' {
  declare module.exports: $Exports<'react-relay/lib'>;
}
declare module 'react-relay/lib/isRelayEnvironment.js' {
  declare module.exports: $Exports<'react-relay/lib/isRelayEnvironment'>;
}
declare module 'react-relay/lib/ReactRelayContainerUtils.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayContainerUtils'>;
}
declare module 'react-relay/lib/ReactRelayContext.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayContext'>;
}
declare module 'react-relay/lib/ReactRelayFragmentContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayFragmentContainer'>;
}
declare module 'react-relay/lib/ReactRelayFragmentMockRenderer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayFragmentMockRenderer'>;
}
declare module 'react-relay/lib/ReactRelayLocalQueryRenderer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayLocalQueryRenderer'>;
}
declare module 'react-relay/lib/ReactRelayPaginationContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayPaginationContainer'>;
}
declare module 'react-relay/lib/ReactRelayQueryFetcher.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayQueryFetcher'>;
}
declare module 'react-relay/lib/ReactRelayQueryRenderer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayQueryRenderer'>;
}
declare module 'react-relay/lib/ReactRelayRefetchContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayRefetchContainer'>;
}
declare module 'react-relay/lib/ReactRelayTestMocker.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayTestMocker'>;
}
declare module 'react-relay/lib/ReactRelayTypes.js' {
  declare module.exports: $Exports<'react-relay/lib/ReactRelayTypes'>;
}
declare module 'react-relay/lib/readContext.js' {
  declare module.exports: $Exports<'react-relay/lib/readContext'>;
}
declare module 'react-relay/lib/relay-experimental/EntryPointContainer.react.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/EntryPointContainer.react'>;
}
declare module 'react-relay/lib/relay-experimental/EntryPointTypes.flow.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/EntryPointTypes.flow'>;
}
declare module 'react-relay/lib/relay-experimental/fetchQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/fetchQuery'>;
}
declare module 'react-relay/lib/relay-experimental/FragmentResource.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/FragmentResource'>;
}
declare module 'react-relay/lib/relay-experimental/getPaginationMetadata.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/getPaginationMetadata'>;
}
declare module 'react-relay/lib/relay-experimental/getPaginationVariables.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/getPaginationVariables'>;
}
declare module 'react-relay/lib/relay-experimental/getRefetchMetadata.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/getRefetchMetadata'>;
}
declare module 'react-relay/lib/relay-experimental/getValueAtPath.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/getValueAtPath'>;
}
declare module 'react-relay/lib/relay-experimental/index' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental'>;
}
declare module 'react-relay/lib/relay-experimental/index.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental'>;
}
declare module 'react-relay/lib/relay-experimental/InternalLogger.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/InternalLogger'>;
}
declare module 'react-relay/lib/relay-experimental/LazyLoadEntryPointContainer.react.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/LazyLoadEntryPointContainer.react'>;
}
declare module 'react-relay/lib/relay-experimental/LRUCache.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/LRUCache'>;
}
declare module 'react-relay/lib/relay-experimental/MatchContainer.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/MatchContainer'>;
}
declare module 'react-relay/lib/relay-experimental/preloadQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/preloadQuery'>;
}
declare module 'react-relay/lib/relay-experimental/prepareEntryPoint.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/prepareEntryPoint'>;
}
declare module 'react-relay/lib/relay-experimental/ProfilerContext.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/ProfilerContext'>;
}
declare module 'react-relay/lib/relay-experimental/QueryResource.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/QueryResource'>;
}
declare module 'react-relay/lib/relay-experimental/RelayEnvironmentProvider.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/RelayEnvironmentProvider'>;
}
declare module 'react-relay/lib/relay-experimental/useBlockingPaginationFragment.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useBlockingPaginationFragment'>;
}
declare module 'react-relay/lib/relay-experimental/useConnection.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useConnection'>;
}
declare module 'react-relay/lib/relay-experimental/useFetchTrackingRef.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useFetchTrackingRef'>;
}
declare module 'react-relay/lib/relay-experimental/useFragment.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useFragment'>;
}
declare module 'react-relay/lib/relay-experimental/useFragmentNode.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useFragmentNode'>;
}
declare module 'react-relay/lib/relay-experimental/useFragmentNodes.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useFragmentNodes'>;
}
declare module 'react-relay/lib/relay-experimental/useIsMountedRef.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useIsMountedRef'>;
}
declare module 'react-relay/lib/relay-experimental/useIsParentQueryInFlight.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useIsParentQueryInFlight'>;
}
declare module 'react-relay/lib/relay-experimental/useLazyLoadQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useLazyLoadQuery'>;
}
declare module 'react-relay/lib/relay-experimental/useLazyLoadQueryNode.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useLazyLoadQueryNode'>;
}
declare module 'react-relay/lib/relay-experimental/useLegacyPaginationFragment.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useLegacyPaginationFragment'>;
}
declare module 'react-relay/lib/relay-experimental/useLoadMoreFunction.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useLoadMoreFunction'>;
}
declare module 'react-relay/lib/relay-experimental/useMemoOperationDescriptor.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useMemoOperationDescriptor'>;
}
declare module 'react-relay/lib/relay-experimental/useMemoVariables.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useMemoVariables'>;
}
declare module 'react-relay/lib/relay-experimental/usePreloadedQuery.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/usePreloadedQuery'>;
}
declare module 'react-relay/lib/relay-experimental/useRefetchableFragment.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useRefetchableFragment'>;
}
declare module 'react-relay/lib/relay-experimental/useRefetchableFragmentNode.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useRefetchableFragmentNode'>;
}
declare module 'react-relay/lib/relay-experimental/useRelayEnvironment.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useRelayEnvironment'>;
}
declare module 'react-relay/lib/relay-experimental/useStaticFragmentNodeWarning.js' {
  declare module.exports: $Exports<'react-relay/lib/relay-experimental/useStaticFragmentNodeWarning'>;
}
declare module 'react-relay/lib/RelayContext.js' {
  declare module.exports: $Exports<'react-relay/lib/RelayContext'>;
}
declare module 'react-relay/react-relay-hooks.js' {
  declare module.exports: $Exports<'react-relay/react-relay-hooks'>;
}
declare module 'react-relay/react-relay-hooks.min.js' {
  declare module.exports: $Exports<'react-relay/react-relay-hooks.min'>;
}
declare module 'react-relay/react-relay.js' {
  declare module.exports: $Exports<'react-relay/react-relay'>;
}
declare module 'react-relay/react-relay.min.js' {
  declare module.exports: $Exports<'react-relay/react-relay.min'>;
}
declare module 'react-relay/ReactRelayContext.js' {
  declare module.exports: $Exports<'react-relay/ReactRelayContext'>;
}
