// flow-typed signature: 98460881400fb86c3e0cfac767513b85
// flow-typed version: <<STUB>>/relay-compiler_v^2.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-compiler/lib/areEqualOSS' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/ASTCache' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/ASTConvert' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/CodegenDirectory' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/CodegenRunner' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/CodegenTypes' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/CodegenWatcher' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/CodeMarker' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/compileRelayArtifacts' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/dedupeJSONStringify' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/deepMergeAssignments' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/DefaultHandleKey' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/DotGraphQLParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/filterContextForNode' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/FilterDirectivesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/FindGraphQLTags' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/FlattenTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/formatGeneratedModule' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/getFieldDefinition' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/getIdentifierForArgumentValue' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/getIdentifierForSelection' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/getLiteralArgumentValues' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/getModuleName' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/getNormalizationOperationName' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLCompilerContext' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLCompilerProfiler' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLCompilerUserError' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLConsoleReporter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLDerivedFromMetadata' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLIR' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLIRPrinter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLIRTransformer' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLIRTransforms' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLIRVisitor' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLMultiReporter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLReporter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLSchemaUtils' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLValidator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/GraphQLWatchmanClient' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/inferRootArgumentDefinitions' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/InlineFragmentsTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/isEquivalentType' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/murmurHash' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/NormalizationCodeGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/nullthrowsOSS' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/ReaderCodeGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RefineOperationVariablesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayApplyFragmentArgumentTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCodeGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerBin' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerCache' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerError' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerMain' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerPublic' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayCompilerScope' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayConnectionConstants' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayConnectionTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayDeferStreamTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFieldHandleTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFileWriter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFindGraphQLTags' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFlowBabelFactories' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFlowGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayFlowTypeTransformers' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayGenerateIDFieldTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayGenerateTypeNameTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayGraphQLEnumsGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayIRTransforms' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayLanguagePluginInterface' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayLanguagePluginJavaScript' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayMaskTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayMatchTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayRefetchableFragmentTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayRelayDirectiveTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelaySkipHandleFieldTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelaySourceModuleParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelaySplitMatchTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayTransformUtils' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayValidator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/RelayViewerHandleTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/SkipClientFieldTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/SkipRedundantNodesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/SkipUnreachableNodeTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/SourceControl' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/writeRelayGeneratedFile' {
  declare module.exports: any;
}

declare module 'relay-compiler/relay-compiler' {
  declare module.exports: any;
}

declare module 'relay-compiler/relay-compiler.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-compiler/index' {
  declare module.exports: $Exports<'relay-compiler'>;
}
declare module 'relay-compiler/index.js' {
  declare module.exports: $Exports<'relay-compiler'>;
}
declare module 'relay-compiler/lib/areEqualOSS.js' {
  declare module.exports: $Exports<'relay-compiler/lib/areEqualOSS'>;
}
declare module 'relay-compiler/lib/ASTCache.js' {
  declare module.exports: $Exports<'relay-compiler/lib/ASTCache'>;
}
declare module 'relay-compiler/lib/ASTConvert.js' {
  declare module.exports: $Exports<'relay-compiler/lib/ASTConvert'>;
}
declare module 'relay-compiler/lib/CodegenDirectory.js' {
  declare module.exports: $Exports<'relay-compiler/lib/CodegenDirectory'>;
}
declare module 'relay-compiler/lib/CodegenRunner.js' {
  declare module.exports: $Exports<'relay-compiler/lib/CodegenRunner'>;
}
declare module 'relay-compiler/lib/CodegenTypes.js' {
  declare module.exports: $Exports<'relay-compiler/lib/CodegenTypes'>;
}
declare module 'relay-compiler/lib/CodegenWatcher.js' {
  declare module.exports: $Exports<'relay-compiler/lib/CodegenWatcher'>;
}
declare module 'relay-compiler/lib/CodeMarker.js' {
  declare module.exports: $Exports<'relay-compiler/lib/CodeMarker'>;
}
declare module 'relay-compiler/lib/compileRelayArtifacts.js' {
  declare module.exports: $Exports<'relay-compiler/lib/compileRelayArtifacts'>;
}
declare module 'relay-compiler/lib/dedupeJSONStringify.js' {
  declare module.exports: $Exports<'relay-compiler/lib/dedupeJSONStringify'>;
}
declare module 'relay-compiler/lib/deepMergeAssignments.js' {
  declare module.exports: $Exports<'relay-compiler/lib/deepMergeAssignments'>;
}
declare module 'relay-compiler/lib/DefaultHandleKey.js' {
  declare module.exports: $Exports<'relay-compiler/lib/DefaultHandleKey'>;
}
declare module 'relay-compiler/lib/DotGraphQLParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/DotGraphQLParser'>;
}
declare module 'relay-compiler/lib/filterContextForNode.js' {
  declare module.exports: $Exports<'relay-compiler/lib/filterContextForNode'>;
}
declare module 'relay-compiler/lib/FilterDirectivesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/FilterDirectivesTransform'>;
}
declare module 'relay-compiler/lib/FindGraphQLTags.js' {
  declare module.exports: $Exports<'relay-compiler/lib/FindGraphQLTags'>;
}
declare module 'relay-compiler/lib/FlattenTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/FlattenTransform'>;
}
declare module 'relay-compiler/lib/formatGeneratedModule.js' {
  declare module.exports: $Exports<'relay-compiler/lib/formatGeneratedModule'>;
}
declare module 'relay-compiler/lib/getFieldDefinition.js' {
  declare module.exports: $Exports<'relay-compiler/lib/getFieldDefinition'>;
}
declare module 'relay-compiler/lib/getIdentifierForArgumentValue.js' {
  declare module.exports: $Exports<'relay-compiler/lib/getIdentifierForArgumentValue'>;
}
declare module 'relay-compiler/lib/getIdentifierForSelection.js' {
  declare module.exports: $Exports<'relay-compiler/lib/getIdentifierForSelection'>;
}
declare module 'relay-compiler/lib/getLiteralArgumentValues.js' {
  declare module.exports: $Exports<'relay-compiler/lib/getLiteralArgumentValues'>;
}
declare module 'relay-compiler/lib/getModuleName.js' {
  declare module.exports: $Exports<'relay-compiler/lib/getModuleName'>;
}
declare module 'relay-compiler/lib/getNormalizationOperationName.js' {
  declare module.exports: $Exports<'relay-compiler/lib/getNormalizationOperationName'>;
}
declare module 'relay-compiler/lib/GraphQLCompilerContext.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLCompilerContext'>;
}
declare module 'relay-compiler/lib/GraphQLCompilerProfiler.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLCompilerProfiler'>;
}
declare module 'relay-compiler/lib/GraphQLCompilerUserError.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLCompilerUserError'>;
}
declare module 'relay-compiler/lib/GraphQLConsoleReporter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLConsoleReporter'>;
}
declare module 'relay-compiler/lib/GraphQLDerivedFromMetadata.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLDerivedFromMetadata'>;
}
declare module 'relay-compiler/lib/GraphQLIR.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLIR'>;
}
declare module 'relay-compiler/lib/GraphQLIRPrinter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLIRPrinter'>;
}
declare module 'relay-compiler/lib/GraphQLIRTransformer.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLIRTransformer'>;
}
declare module 'relay-compiler/lib/GraphQLIRTransforms.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLIRTransforms'>;
}
declare module 'relay-compiler/lib/GraphQLIRVisitor.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLIRVisitor'>;
}
declare module 'relay-compiler/lib/GraphQLMultiReporter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLMultiReporter'>;
}
declare module 'relay-compiler/lib/GraphQLReporter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLReporter'>;
}
declare module 'relay-compiler/lib/GraphQLSchemaUtils.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLSchemaUtils'>;
}
declare module 'relay-compiler/lib/GraphQLValidator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLValidator'>;
}
declare module 'relay-compiler/lib/GraphQLWatchmanClient.js' {
  declare module.exports: $Exports<'relay-compiler/lib/GraphQLWatchmanClient'>;
}
declare module 'relay-compiler/lib/inferRootArgumentDefinitions.js' {
  declare module.exports: $Exports<'relay-compiler/lib/inferRootArgumentDefinitions'>;
}
declare module 'relay-compiler/lib/InlineFragmentsTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/InlineFragmentsTransform'>;
}
declare module 'relay-compiler/lib/isEquivalentType.js' {
  declare module.exports: $Exports<'relay-compiler/lib/isEquivalentType'>;
}
declare module 'relay-compiler/lib/murmurHash.js' {
  declare module.exports: $Exports<'relay-compiler/lib/murmurHash'>;
}
declare module 'relay-compiler/lib/NormalizationCodeGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/NormalizationCodeGenerator'>;
}
declare module 'relay-compiler/lib/nullthrowsOSS.js' {
  declare module.exports: $Exports<'relay-compiler/lib/nullthrowsOSS'>;
}
declare module 'relay-compiler/lib/ReaderCodeGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/ReaderCodeGenerator'>;
}
declare module 'relay-compiler/lib/RefineOperationVariablesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RefineOperationVariablesTransform'>;
}
declare module 'relay-compiler/lib/RelayApplyFragmentArgumentTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayApplyFragmentArgumentTransform'>;
}
declare module 'relay-compiler/lib/RelayCodeGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCodeGenerator'>;
}
declare module 'relay-compiler/lib/RelayCompilerBin.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerBin'>;
}
declare module 'relay-compiler/lib/RelayCompilerCache.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerCache'>;
}
declare module 'relay-compiler/lib/RelayCompilerError.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerError'>;
}
declare module 'relay-compiler/lib/RelayCompilerMain.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerMain'>;
}
declare module 'relay-compiler/lib/RelayCompilerPublic.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerPublic'>;
}
declare module 'relay-compiler/lib/RelayCompilerScope.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayCompilerScope'>;
}
declare module 'relay-compiler/lib/RelayConnectionConstants.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayConnectionConstants'>;
}
declare module 'relay-compiler/lib/RelayConnectionTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayConnectionTransform'>;
}
declare module 'relay-compiler/lib/RelayDeferStreamTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayDeferStreamTransform'>;
}
declare module 'relay-compiler/lib/RelayFieldHandleTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFieldHandleTransform'>;
}
declare module 'relay-compiler/lib/RelayFileWriter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFileWriter'>;
}
declare module 'relay-compiler/lib/RelayFindGraphQLTags.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFindGraphQLTags'>;
}
declare module 'relay-compiler/lib/RelayFlowBabelFactories.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFlowBabelFactories'>;
}
declare module 'relay-compiler/lib/RelayFlowGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFlowGenerator'>;
}
declare module 'relay-compiler/lib/RelayFlowTypeTransformers.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayFlowTypeTransformers'>;
}
declare module 'relay-compiler/lib/RelayGenerateIDFieldTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayGenerateIDFieldTransform'>;
}
declare module 'relay-compiler/lib/RelayGenerateTypeNameTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayGenerateTypeNameTransform'>;
}
declare module 'relay-compiler/lib/RelayGraphQLEnumsGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayGraphQLEnumsGenerator'>;
}
declare module 'relay-compiler/lib/RelayIRTransforms.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayIRTransforms'>;
}
declare module 'relay-compiler/lib/RelayLanguagePluginInterface.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayLanguagePluginInterface'>;
}
declare module 'relay-compiler/lib/RelayLanguagePluginJavaScript.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayLanguagePluginJavaScript'>;
}
declare module 'relay-compiler/lib/RelayMaskTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayMaskTransform'>;
}
declare module 'relay-compiler/lib/RelayMatchTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayMatchTransform'>;
}
declare module 'relay-compiler/lib/RelayParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayParser'>;
}
declare module 'relay-compiler/lib/RelayRefetchableFragmentTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayRefetchableFragmentTransform'>;
}
declare module 'relay-compiler/lib/RelayRelayDirectiveTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayRelayDirectiveTransform'>;
}
declare module 'relay-compiler/lib/RelaySkipHandleFieldTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelaySkipHandleFieldTransform'>;
}
declare module 'relay-compiler/lib/RelaySourceModuleParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelaySourceModuleParser'>;
}
declare module 'relay-compiler/lib/RelaySplitMatchTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelaySplitMatchTransform'>;
}
declare module 'relay-compiler/lib/RelayTransformUtils.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayTransformUtils'>;
}
declare module 'relay-compiler/lib/RelayValidator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayValidator'>;
}
declare module 'relay-compiler/lib/RelayViewerHandleTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/RelayViewerHandleTransform'>;
}
declare module 'relay-compiler/lib/SkipClientFieldTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/SkipClientFieldTransform'>;
}
declare module 'relay-compiler/lib/SkipRedundantNodesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/SkipRedundantNodesTransform'>;
}
declare module 'relay-compiler/lib/SkipUnreachableNodeTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/SkipUnreachableNodeTransform'>;
}
declare module 'relay-compiler/lib/SourceControl.js' {
  declare module.exports: $Exports<'relay-compiler/lib/SourceControl'>;
}
declare module 'relay-compiler/lib/writeRelayGeneratedFile.js' {
  declare module.exports: $Exports<'relay-compiler/lib/writeRelayGeneratedFile'>;
}
declare module 'relay-compiler/relay-compiler.js' {
  declare module.exports: $Exports<'relay-compiler/relay-compiler'>;
}
declare module 'relay-compiler/relay-compiler.min.js' {
  declare module.exports: $Exports<'relay-compiler/relay-compiler.min'>;
}
