// flow-typed signature: 03af712b269e972477c7db3420d90e72
// flow-typed version: <<STUB>>/relay-compiler_v8.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-compiler/lib/bin/__fixtures__/plugin-module' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/bin/RelayCompilerBin' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/bin/RelayCompilerMain' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/CodegenDirectory' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/CodegenRunner' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/CodegenTypes' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/CodegenWatcher' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/compileRelayArtifacts' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/createPrintRequireModuleDependency' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/NormalizationCodeGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/ReaderCodeGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/RelayCodeGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/RelayFileWriter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/SourceControl' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/codegen/writeRelayGeneratedFile' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/ASTCache' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/ASTConvert' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/CompilerContext' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/CompilerError' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/DotGraphQLParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/filterContextForNode' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/getFieldDefinition' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/getIdentifierForArgumentValue' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/getIdentifierForSelection' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/getLiteralArgumentValues' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/getNormalizationOperationName' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLCompilerContext' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLCompilerProfiler' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLDerivedFromMetadata' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLIR' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLIRPrinter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLIRTransformer' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLIRValidator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLIRVisitor' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/GraphQLWatchmanClient' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/inferRootArgumentDefinitions' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/IR' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/IRPrinter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/IRTransformer' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/IRValidator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/IRVisitor' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/JSModuleParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/RelayCompilerError' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/RelayCompilerScope' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/RelayFindGraphQLTags' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/RelayGraphQLEnumsGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/RelayIRTransforms' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/RelayParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/RelaySourceModuleParser' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/Schema' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/core/SchemaUtils' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/language/javascript/FindGraphQLTags' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/language/javascript/formatGeneratedModule' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/language/javascript/RelayFlowBabelFactories' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/language/javascript/RelayFlowGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/language/javascript/RelayFlowTypeTransformers' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/language/javascript/RelayLanguagePluginJavaScript' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/language/RelayLanguagePluginInterface' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/reporters/ConsoleReporter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/reporters/MultiReporter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/reporters/Reporter' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/Artifacts' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/BufferedFilesystem' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/compileArtifacts' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/extractAST' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/getChangedNodeNames' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/getSchemaInstance' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/GraphQLASTNodeGroup' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/GraphQLASTUtils' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/GraphQLNodeMap' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/Sources' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/StrictMap' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/runner/types' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/ApplyFragmentArgumentTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/ClientExtensionsTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/ConnectionFieldTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/ConnectionTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/DeferStreamTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/DisallowIdAsAlias' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/FieldHandleTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/FilterDirectivesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/FlattenTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/GenerateIDFieldTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/GenerateTypeNameTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/InlineDataFragmentTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/InlineFragmentsTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/MaskTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/MatchTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/query-generators' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/query-generators/NodeQueryGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/query-generators/QueryQueryGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/query-generators/utils' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/query-generators/ViewerQueryGenerator' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/RefetchableFragmentTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/RelayDirectiveTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/SkipClientExtensionsTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/SkipHandleFieldTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/SkipRedundantNodesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/SkipUnreachableNodeTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/SkipUnusedVariablesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/SplitModuleImportTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/TestOperationTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/TransformUtils' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/ValidateGlobalVariablesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/ValidateRequiredArgumentsTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/ValidateServerOnlyDirectivesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/transforms/ValidateUnusedVariablesTransform' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/areEqualOSS' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/CodeMarker' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/dedupeJSONStringify' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/DefaultHandleKey' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/getDefinitionNodeHash' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/getModuleName' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/joinArgumentDefinitions' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/md5' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/murmurHash' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/nullthrowsOSS' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/orList' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/partitionArray' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/RelayCompilerCache' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/Rollout' {
  declare module.exports: any;
}

declare module 'relay-compiler/lib/util/TimeReporter' {
  declare module.exports: any;
}

declare module 'relay-compiler/relay-compiler' {
  declare module.exports: any;
}

declare module 'relay-compiler/relay-compiler.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-compiler/index' {
  declare module.exports: $Exports<'relay-compiler'>;
}
declare module 'relay-compiler/index.js' {
  declare module.exports: $Exports<'relay-compiler'>;
}
declare module 'relay-compiler/lib/bin/__fixtures__/plugin-module.js' {
  declare module.exports: $Exports<'relay-compiler/lib/bin/__fixtures__/plugin-module'>;
}
declare module 'relay-compiler/lib/bin/RelayCompilerBin.js' {
  declare module.exports: $Exports<'relay-compiler/lib/bin/RelayCompilerBin'>;
}
declare module 'relay-compiler/lib/bin/RelayCompilerMain.js' {
  declare module.exports: $Exports<'relay-compiler/lib/bin/RelayCompilerMain'>;
}
declare module 'relay-compiler/lib/codegen/CodegenDirectory.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/CodegenDirectory'>;
}
declare module 'relay-compiler/lib/codegen/CodegenRunner.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/CodegenRunner'>;
}
declare module 'relay-compiler/lib/codegen/CodegenTypes.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/CodegenTypes'>;
}
declare module 'relay-compiler/lib/codegen/CodegenWatcher.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/CodegenWatcher'>;
}
declare module 'relay-compiler/lib/codegen/compileRelayArtifacts.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/compileRelayArtifacts'>;
}
declare module 'relay-compiler/lib/codegen/createPrintRequireModuleDependency.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/createPrintRequireModuleDependency'>;
}
declare module 'relay-compiler/lib/codegen/NormalizationCodeGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/NormalizationCodeGenerator'>;
}
declare module 'relay-compiler/lib/codegen/ReaderCodeGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/ReaderCodeGenerator'>;
}
declare module 'relay-compiler/lib/codegen/RelayCodeGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/RelayCodeGenerator'>;
}
declare module 'relay-compiler/lib/codegen/RelayFileWriter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/RelayFileWriter'>;
}
declare module 'relay-compiler/lib/codegen/SourceControl.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/SourceControl'>;
}
declare module 'relay-compiler/lib/codegen/writeRelayGeneratedFile.js' {
  declare module.exports: $Exports<'relay-compiler/lib/codegen/writeRelayGeneratedFile'>;
}
declare module 'relay-compiler/lib/core/ASTCache.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/ASTCache'>;
}
declare module 'relay-compiler/lib/core/ASTConvert.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/ASTConvert'>;
}
declare module 'relay-compiler/lib/core/CompilerContext.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/CompilerContext'>;
}
declare module 'relay-compiler/lib/core/CompilerError.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/CompilerError'>;
}
declare module 'relay-compiler/lib/core/DotGraphQLParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/DotGraphQLParser'>;
}
declare module 'relay-compiler/lib/core/filterContextForNode.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/filterContextForNode'>;
}
declare module 'relay-compiler/lib/core/getFieldDefinition.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/getFieldDefinition'>;
}
declare module 'relay-compiler/lib/core/getIdentifierForArgumentValue.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/getIdentifierForArgumentValue'>;
}
declare module 'relay-compiler/lib/core/getIdentifierForSelection.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/getIdentifierForSelection'>;
}
declare module 'relay-compiler/lib/core/getLiteralArgumentValues.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/getLiteralArgumentValues'>;
}
declare module 'relay-compiler/lib/core/getNormalizationOperationName.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/getNormalizationOperationName'>;
}
declare module 'relay-compiler/lib/core/GraphQLCompilerContext.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLCompilerContext'>;
}
declare module 'relay-compiler/lib/core/GraphQLCompilerProfiler.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLCompilerProfiler'>;
}
declare module 'relay-compiler/lib/core/GraphQLDerivedFromMetadata.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLDerivedFromMetadata'>;
}
declare module 'relay-compiler/lib/core/GraphQLIR.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLIR'>;
}
declare module 'relay-compiler/lib/core/GraphQLIRPrinter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLIRPrinter'>;
}
declare module 'relay-compiler/lib/core/GraphQLIRTransformer.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLIRTransformer'>;
}
declare module 'relay-compiler/lib/core/GraphQLIRValidator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLIRValidator'>;
}
declare module 'relay-compiler/lib/core/GraphQLIRVisitor.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLIRVisitor'>;
}
declare module 'relay-compiler/lib/core/GraphQLWatchmanClient.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/GraphQLWatchmanClient'>;
}
declare module 'relay-compiler/lib/core/inferRootArgumentDefinitions.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/inferRootArgumentDefinitions'>;
}
declare module 'relay-compiler/lib/core/IR.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/IR'>;
}
declare module 'relay-compiler/lib/core/IRPrinter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/IRPrinter'>;
}
declare module 'relay-compiler/lib/core/IRTransformer.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/IRTransformer'>;
}
declare module 'relay-compiler/lib/core/IRValidator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/IRValidator'>;
}
declare module 'relay-compiler/lib/core/IRVisitor.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/IRVisitor'>;
}
declare module 'relay-compiler/lib/core/JSModuleParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/JSModuleParser'>;
}
declare module 'relay-compiler/lib/core/RelayCompilerError.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/RelayCompilerError'>;
}
declare module 'relay-compiler/lib/core/RelayCompilerScope.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/RelayCompilerScope'>;
}
declare module 'relay-compiler/lib/core/RelayFindGraphQLTags.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/RelayFindGraphQLTags'>;
}
declare module 'relay-compiler/lib/core/RelayGraphQLEnumsGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/RelayGraphQLEnumsGenerator'>;
}
declare module 'relay-compiler/lib/core/RelayIRTransforms.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/RelayIRTransforms'>;
}
declare module 'relay-compiler/lib/core/RelayParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/RelayParser'>;
}
declare module 'relay-compiler/lib/core/RelaySourceModuleParser.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/RelaySourceModuleParser'>;
}
declare module 'relay-compiler/lib/core/Schema.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/Schema'>;
}
declare module 'relay-compiler/lib/core/SchemaUtils.js' {
  declare module.exports: $Exports<'relay-compiler/lib/core/SchemaUtils'>;
}
declare module 'relay-compiler/lib/index' {
  declare module.exports: $Exports<'relay-compiler/lib'>;
}
declare module 'relay-compiler/lib/index.js' {
  declare module.exports: $Exports<'relay-compiler/lib'>;
}
declare module 'relay-compiler/lib/language/javascript/FindGraphQLTags.js' {
  declare module.exports: $Exports<'relay-compiler/lib/language/javascript/FindGraphQLTags'>;
}
declare module 'relay-compiler/lib/language/javascript/formatGeneratedModule.js' {
  declare module.exports: $Exports<'relay-compiler/lib/language/javascript/formatGeneratedModule'>;
}
declare module 'relay-compiler/lib/language/javascript/RelayFlowBabelFactories.js' {
  declare module.exports: $Exports<'relay-compiler/lib/language/javascript/RelayFlowBabelFactories'>;
}
declare module 'relay-compiler/lib/language/javascript/RelayFlowGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/language/javascript/RelayFlowGenerator'>;
}
declare module 'relay-compiler/lib/language/javascript/RelayFlowTypeTransformers.js' {
  declare module.exports: $Exports<'relay-compiler/lib/language/javascript/RelayFlowTypeTransformers'>;
}
declare module 'relay-compiler/lib/language/javascript/RelayLanguagePluginJavaScript.js' {
  declare module.exports: $Exports<'relay-compiler/lib/language/javascript/RelayLanguagePluginJavaScript'>;
}
declare module 'relay-compiler/lib/language/RelayLanguagePluginInterface.js' {
  declare module.exports: $Exports<'relay-compiler/lib/language/RelayLanguagePluginInterface'>;
}
declare module 'relay-compiler/lib/reporters/ConsoleReporter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/reporters/ConsoleReporter'>;
}
declare module 'relay-compiler/lib/reporters/MultiReporter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/reporters/MultiReporter'>;
}
declare module 'relay-compiler/lib/reporters/Reporter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/reporters/Reporter'>;
}
declare module 'relay-compiler/lib/runner/Artifacts.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/Artifacts'>;
}
declare module 'relay-compiler/lib/runner/BufferedFilesystem.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/BufferedFilesystem'>;
}
declare module 'relay-compiler/lib/runner/compileArtifacts.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/compileArtifacts'>;
}
declare module 'relay-compiler/lib/runner/extractAST.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/extractAST'>;
}
declare module 'relay-compiler/lib/runner/getChangedNodeNames.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/getChangedNodeNames'>;
}
declare module 'relay-compiler/lib/runner/getSchemaInstance.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/getSchemaInstance'>;
}
declare module 'relay-compiler/lib/runner/GraphQLASTNodeGroup.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/GraphQLASTNodeGroup'>;
}
declare module 'relay-compiler/lib/runner/GraphQLASTUtils.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/GraphQLASTUtils'>;
}
declare module 'relay-compiler/lib/runner/GraphQLNodeMap.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/GraphQLNodeMap'>;
}
declare module 'relay-compiler/lib/runner/Sources.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/Sources'>;
}
declare module 'relay-compiler/lib/runner/StrictMap.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/StrictMap'>;
}
declare module 'relay-compiler/lib/runner/types.js' {
  declare module.exports: $Exports<'relay-compiler/lib/runner/types'>;
}
declare module 'relay-compiler/lib/transforms/ApplyFragmentArgumentTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/ApplyFragmentArgumentTransform'>;
}
declare module 'relay-compiler/lib/transforms/ClientExtensionsTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/ClientExtensionsTransform'>;
}
declare module 'relay-compiler/lib/transforms/ConnectionFieldTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/ConnectionFieldTransform'>;
}
declare module 'relay-compiler/lib/transforms/ConnectionTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/ConnectionTransform'>;
}
declare module 'relay-compiler/lib/transforms/DeferStreamTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/DeferStreamTransform'>;
}
declare module 'relay-compiler/lib/transforms/DisallowIdAsAlias.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/DisallowIdAsAlias'>;
}
declare module 'relay-compiler/lib/transforms/FieldHandleTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/FieldHandleTransform'>;
}
declare module 'relay-compiler/lib/transforms/FilterDirectivesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/FilterDirectivesTransform'>;
}
declare module 'relay-compiler/lib/transforms/FlattenTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/FlattenTransform'>;
}
declare module 'relay-compiler/lib/transforms/GenerateIDFieldTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/GenerateIDFieldTransform'>;
}
declare module 'relay-compiler/lib/transforms/GenerateTypeNameTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/GenerateTypeNameTransform'>;
}
declare module 'relay-compiler/lib/transforms/InlineDataFragmentTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/InlineDataFragmentTransform'>;
}
declare module 'relay-compiler/lib/transforms/InlineFragmentsTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/InlineFragmentsTransform'>;
}
declare module 'relay-compiler/lib/transforms/MaskTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/MaskTransform'>;
}
declare module 'relay-compiler/lib/transforms/MatchTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/MatchTransform'>;
}
declare module 'relay-compiler/lib/transforms/query-generators/index' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/query-generators'>;
}
declare module 'relay-compiler/lib/transforms/query-generators/index.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/query-generators'>;
}
declare module 'relay-compiler/lib/transforms/query-generators/NodeQueryGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/query-generators/NodeQueryGenerator'>;
}
declare module 'relay-compiler/lib/transforms/query-generators/QueryQueryGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/query-generators/QueryQueryGenerator'>;
}
declare module 'relay-compiler/lib/transforms/query-generators/utils.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/query-generators/utils'>;
}
declare module 'relay-compiler/lib/transforms/query-generators/ViewerQueryGenerator.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/query-generators/ViewerQueryGenerator'>;
}
declare module 'relay-compiler/lib/transforms/RefetchableFragmentTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/RefetchableFragmentTransform'>;
}
declare module 'relay-compiler/lib/transforms/RelayDirectiveTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/RelayDirectiveTransform'>;
}
declare module 'relay-compiler/lib/transforms/SkipClientExtensionsTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/SkipClientExtensionsTransform'>;
}
declare module 'relay-compiler/lib/transforms/SkipHandleFieldTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/SkipHandleFieldTransform'>;
}
declare module 'relay-compiler/lib/transforms/SkipRedundantNodesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/SkipRedundantNodesTransform'>;
}
declare module 'relay-compiler/lib/transforms/SkipUnreachableNodeTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/SkipUnreachableNodeTransform'>;
}
declare module 'relay-compiler/lib/transforms/SkipUnusedVariablesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/SkipUnusedVariablesTransform'>;
}
declare module 'relay-compiler/lib/transforms/SplitModuleImportTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/SplitModuleImportTransform'>;
}
declare module 'relay-compiler/lib/transforms/TestOperationTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/TestOperationTransform'>;
}
declare module 'relay-compiler/lib/transforms/TransformUtils.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/TransformUtils'>;
}
declare module 'relay-compiler/lib/transforms/ValidateGlobalVariablesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/ValidateGlobalVariablesTransform'>;
}
declare module 'relay-compiler/lib/transforms/ValidateRequiredArgumentsTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/ValidateRequiredArgumentsTransform'>;
}
declare module 'relay-compiler/lib/transforms/ValidateServerOnlyDirectivesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/ValidateServerOnlyDirectivesTransform'>;
}
declare module 'relay-compiler/lib/transforms/ValidateUnusedVariablesTransform.js' {
  declare module.exports: $Exports<'relay-compiler/lib/transforms/ValidateUnusedVariablesTransform'>;
}
declare module 'relay-compiler/lib/util/areEqualOSS.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/areEqualOSS'>;
}
declare module 'relay-compiler/lib/util/CodeMarker.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/CodeMarker'>;
}
declare module 'relay-compiler/lib/util/dedupeJSONStringify.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/dedupeJSONStringify'>;
}
declare module 'relay-compiler/lib/util/DefaultHandleKey.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/DefaultHandleKey'>;
}
declare module 'relay-compiler/lib/util/getDefinitionNodeHash.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/getDefinitionNodeHash'>;
}
declare module 'relay-compiler/lib/util/getModuleName.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/getModuleName'>;
}
declare module 'relay-compiler/lib/util/joinArgumentDefinitions.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/joinArgumentDefinitions'>;
}
declare module 'relay-compiler/lib/util/md5.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/md5'>;
}
declare module 'relay-compiler/lib/util/murmurHash.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/murmurHash'>;
}
declare module 'relay-compiler/lib/util/nullthrowsOSS.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/nullthrowsOSS'>;
}
declare module 'relay-compiler/lib/util/orList.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/orList'>;
}
declare module 'relay-compiler/lib/util/partitionArray.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/partitionArray'>;
}
declare module 'relay-compiler/lib/util/RelayCompilerCache.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/RelayCompilerCache'>;
}
declare module 'relay-compiler/lib/util/Rollout.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/Rollout'>;
}
declare module 'relay-compiler/lib/util/TimeReporter.js' {
  declare module.exports: $Exports<'relay-compiler/lib/util/TimeReporter'>;
}
declare module 'relay-compiler/relay-compiler.js' {
  declare module.exports: $Exports<'relay-compiler/relay-compiler'>;
}
declare module 'relay-compiler/relay-compiler.min.js' {
  declare module.exports: $Exports<'relay-compiler/relay-compiler.min'>;
}
