// flow-typed signature: e1a8affc971fc471306a7a1a8c8af055
// flow-typed version: <<STUB>>/todomvc-app-css_v^2.1.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'todomvc-app-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'todomvc-app-css' {
  declare module.exports: any;
}
