// flow-typed signature: f6a19cf1e25dedf4b7c0a1d3aa3f4d61
// flow-typed version: <<STUB>>/todomvc-app-css_v^2.3.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'todomvc-app-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'todomvc-app-css' {
  declare module.exports: any;
}
