// flow-typed signature: f08666ad0b00d16b281e58074c2c3ab5
// flow-typed version: <<STUB>>/todomvc-app-css_v^2.2.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'todomvc-app-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'todomvc-app-css' {
  declare module.exports: any;
}
