# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: CI

on: [push, pull_request]

jobs:
  build:
    name: Tests (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install watchman
        run: |
          mkdir watchman
          cd watchman
          curl -L -O 'https://github.com/facebook/watchman/releases/download/v2026.05.11.00/watchman-v2026.05.11.00-linux.zip'
          unzip watchman-v2026.05.11.00-linux.zip
          cd watchman-v2026.05.11.00-linux
          sudo mkdir -p /usr/local/{bin,lib} /usr/local/var/run/watchman
          sudo cp bin/* /usr/local/bin
          sudo cp lib/* /usr/local/lib
          sudo chmod 755 /usr/local/bin/watchman
          sudo chmod 2777 /usr/local/var/run/watchman
      - name: yarn install (todo)
        working-directory: todo
        run: yarn install --frozen-lockfile
      - name: CI (todo)
        working-directory: todo
        run: yarn run ci
